### ISSUE TITLE
wont start 

### ISSUE THREAD

**Issue by lolusmaximus** [Jorge332/SpleeterBox#1]
![error](https://user-images.githubusercontent.com/58622367/70372868-a189e380-18e4-11ea-8e22-56c51400db97.JPG)

- USB audio device used (!)

**Comment by andrewshi910** [comment]
experiencing the same here

**Comment by Jorge332** [comment]
You guys made sure to have Spleeter working properly before downloading this implementation?

**Comment by Jorge332** [comment]
I mean, is it working when you use the command prompt to separate files?

**Comment by andrewshi910** [comment]
for me, yes. i am able to separate using powershell.

**Comment by Jorge332** [comment]
Guys I've already found the issue, and it's fixed now, just download the latest version of the implementation and it should work just fine

**Comment by Jorge332** [comment]
Just let me know if it worked for you guys, send me an email just to make sure

**Comment by andrewshi910** [comment]
it worked!
thanks for the swift response and fix

**Comment by Jorge332** [comment]
You're welcome, thanks to you guys for let me know about the issue :)
