### ISSUE TITLE
ModuleNotFoundError: No module named 'spleeter'

### ISSUE THREAD

**Issue by iAmSpohr** [Jorge332/SpleeterBox#3]
I'm running the .exe file but nothing happens. Running the .py file through powershell, I get the following error:
```
Traceback (most recent call last):
  File ".\spleeterBox.py", line 11, in <module>
    from spleeter.separator import Separator
ModuleNotFoundError: No module named 'spleeter'
```

Please have a look at this

EDIT: ah sorry, my bad, realized I need spleeter installed to do this :) would u add it to the readme?

**Comment by Jorge332** [comment]
Don't worry, In the First Use Section It says it, but It might be not noticeable enough so I added it to the very begging of the Read Me lol, hope the UI helps you :D
